### PR TITLE
Include anti_ssp case generator

### PR DESCRIPTION
**Pull request by MiSawa**
Oops somehow it didn't pick this commit.
This change replaces the hardcoded anti-ssp case with the generator of that case.

### CODE REVIEW

**Comment by yosupo06** [comment]
It seems that the content of this case is changed (because hash.json is changed). Please confirm that it is your intended, thanks!

**Comment by MiSawa** [comment]
Yes; I found that the parameter I've used for the _.in_ file wasn't tight. In the _.cpp_ generator, I've made it search for the best parameter and thus the case has changed.
I've verified locally that changing param makes generator generate same file.
Also... so long as ssp solution TLEs, it's fine-ish.

**Comment by yosupo06** [comment]
I see, that make sense. Thanks!

**Comment by yosupo06** [comment]
It seems that github actions are downed (by twitter searcing) and unfortunately, actions downed before merging previous PR so we can not deploy problems... please wait ...

**Pull request merged**
