### PR TITLE
Close files using `with` statement

### PR DESCRIPTION
**Pull request by HeRaNO**
Close: #1149

### CODE REVIEW

**Comment by HeRaNO** [comment]
@yosupo06 PTAL

**Comment by yosupo06** [comment]
thanks I just merged a patch for fixing CI error. Please merge origin/master, I hope it resolved CI failure of this MR

**Comment by HeRaNO** [comment]
> thanks I just merged a patch for fixing CI error. Please merge origin/master, I hope it resolved CI failure of this MR

CI green

**Comment by HeRaNO** [comment]
Added a small patch and it's run pretty well. @yosupo06 PTAL, thx

**Comment by yosupo06** [comment]
Thanks! Our CI output is cleaned by this patch

**Pull request merged**
