### PR TITLE
general_weighted_matching

### PR DESCRIPTION
**Pull request by antma**
Maximum weighted matching in general graph: issue #171
English statement, some random tests, verifier, checker  and @min-25 solution.

### CODE REVIEW

**Comment by yosupo06** [comment]
Are min-25's solutions published with some suitable license(e.g. MIT, CC0)?

**Comment by antma** [comment]
> Are min-25's solutions published with some suitable license(e.g. MIT, CC0)?
That is the main problem. I didn't found license in [original source](https://gist.github.com/min-25/b984122f97dd7f72500e0bd6e49906ca). So I just mention him in PR comment and hope he will reply in this thread.

**Comment by min-25** [comment]
No problems to be used.

Some concerns:
- (Although I have tested it with many inputs,) It might return an incorrect answer or raise error in some situation.
- There is a concise and shorter O(n^3) code in uoj 0081.

**Comment by antma** [comment]
> It might return an incorrect answer or raise error in some situation.

I compared it with [library code](https://github.com/ornicar/lila/blob/master/modules/common/src/main/WMMatching.scala).
It produced correct results for current test set and other 1000 small random tests.
Later when problem will available on OJ, I will try to add some counter tests .
And I hope someone translate _task.md_ into japanese.

**Comment by yosupo06** [comment]
Thanks @antma & @min-25 ! I merged.

> And another question is should I commit mine alternate solution written in Rust?

Don't have to (actually, our generate.py can only handle cpp code now)

**Pull request merged**
