### PR TITLE
add testcase

### PR DESCRIPTION
**Pull request by maspypy**
https://github.com/yosupo06/library-checker-problems/issues/751
https://github.com/yosupo06/library-checker-problems/issues/881

### CODE REVIEW

**Comment by TonalidadeHidrica** [comment]
@maspypy Can we now close #751 and #881 already?

**Comment by maspypy** [comment]
Yes

**Comment by TonalidadeHidrica** [comment]
Who has a permission to close them?

**Comment by maspypy** [comment]
I think I don't have the permission, and I don't know who have it.
(at least @yosupo06 can do it. )

I think many other issues can be closed.

**Pull request merged**
